### ISSUE TITLE
Adding Catch to the project?

### ISSUE THREAD

**Issue by ferkulat** [FlorianRappl/CmdParser#12]
Hello Florian,

I would like to contribute, but Catch is missing.
Maybe you installed it as package to your OS?
Would you mind to add the Catch header to the project?
Either by 
1. just download and commit or
2. via git submodule?
3. biicode (I don't know, if this would be possible)

In my projects I prefer case 1.

For cases 1. or 2. I could make a pull request for that. if you want.
For case 3. I don't know biicode enough yet.

Thank you in advance

**Comment by FlorianRappl** [comment]
Catch was introduced by bii (your 3rd option) - a package manager. bii is, unfortunately, now dead.

Yes, just go for 1) - since catch is a header only lib it is sufficient to add a snapshot. Thanks for the issue and the PR! Much appreciated 👍

**Comment by ferkulat** [comment]
If bii is dead, how about removing all the bii stuff?
1. Since The CMakeLists.txt is tracket by git, when i run bii on it for my IDE (CLion), it changes the CMakeLists.txt.
And when I want to do things with git (stash, switch branch,...) this blocks.
And I have to work around this all the time.

2. Since Catch was the reason for biicode and is now part of the source, biicode is not needed anymore
3. It would remove this manual step to invoke bii to get a working state

I would also make this changes in CMakeLists.txt when I add Catch.

Greetings

**Comment by FlorianRappl** [comment]
Yes, please go ahead. This is really good!

**Comment by FlorianRappl** [comment]
(also if you have some other ideas how to distribute header-only libs for C++ then either write me or just publish it - I guess we could also set up some free CI to distribute it automatically)

**Comment by FlorianRappl** [comment]
This is awesome! Thanks for PR #13! 🍺
