### ISSUE TITLE
Sign conversion compilation warnings

### ISSUE THREAD

**Issue by Lecrapouille** [FlorianRappl/CmdParser#18]
Not a bug bust just warnings triggered when compiling with -Wsign-conversion option. You should replace `int` by `size_t` in two lines:
```
~Parser() { 
for (size_t i = 0, n = _commands.size(); i < n; ++i) { ...
```
and
```
bool run(std::ostream& output, std::ostream& error) { ...
for (size_t i = 0, n = _arguments.size(); i < n; ++i) {
```

Thanks for this lib !

**Comment by FlorianRappl** [comment]
Thanks for reporting this (and sorry for the delayed response; forgot about it ...).

Sounds reasonable! Consider it done.
