### ISSUE TITLE
Licensing is too restrictive

### ISSUE THREAD

**Issue by divyekapoor** [FlorianRappl/CmdParser#2]
Hi Florian,
   You have a nice command line parsing library here, but it's a bit too restrictive in its licensing (GPLv3: it's incompatible with and imposes upon several other licenses). Would you consider relicensing the library under Public Domain or the MIT license?

Thanks!
Divye

**Comment by FlorianRappl** [comment]
Sure thing. I'll change it to MIT!

Thanks for your suggestion.
