### ISSUE TITLE
Do you mind tagging a version?

### ISSUE THREAD

**Issue by DmitryFromDubna** [FlorianRappl/CmdParser#21]
Hello! This is a nice and small library and we'd like to use it in our product, but we need to specify a particular version in the product license attributions. Can you tag some recent stable version? Currently you only have v1.0 which is 4 years old and uses GPLv3 license. Thank you!

**Comment by FlorianRappl** [comment]
Nope I don't mind: https://github.com/FlorianRappl/CmdParser/releases/tag/v1.0.0

There you go!

Hope that helps :)

**Comment by DmitryFromDubna** [comment]
Cool, thank you!
