### ISSUE TITLE
Allow to specify general program description

### ISSUE THREAD

**Issue by adomasbaliuka** [FlorianRappl/CmdParser#27]
Currently, it seems that the command line parser only deals with descriptions of command line parameters.

Most command line parsers allow to specify a general description of what the program does, which is usually displayed in the help text above the argument descriptions. This does not seem to be supported at the moment, although it should be easy to implement.

**Comment by FlorianRappl** [comment]
That's right - it does not show that. Do you want to provide a PR with that? Would be appreciated!

**Comment by adomasbaliuka** [comment]
PR #28

**Comment by FlorianRappl** [comment]
Thanks @adomasbaliuka !
