### ISSUE TITLE
Plenty of compilation warnings

### ISSUE THREAD

**Issue by Lecrapouille** [FlorianRappl/CmdParser#31]
Please fix warnings obtained when compiling with these flags: `-Wunknown-pragmas -Wshadow`

**Comment by FlorianRappl** [comment]
I'm not working for you. If you want to contribute something you can make a PR.

**Comment by Lecrapouille** [comment]
Not working for me, just your lib has shadows vars, up to you not fix them!

**Comment by FlorianRappl** [comment]
You don't understand open-source and your self-centered view of the world is just inappropriate. Banned.
