### ISSUE TITLE
Positional Arguments

### ISSUE THREAD

**Issue by rhd** [FlorianRappl/CmdParser#5]
Hi, is it possible to get positional arguments?

`myapp --someflag -a2 FILE1 FILE2 FILE3...`

For example.

**Comment by FlorianRappl** [comment]
Yes, I think what you want is essentially a list, right? If you use `std::list<T>` (in this case `T` being `std::string`) it should work.

**Comment by rhd** [comment]
Hi @FlorianRappl 

Yes, a list but without a preceding flag.

Are you talking about something like this?
`myapp --someflag -a2 --files FILE1 FILE2 FILE3`

Maybe a more clear example is the `mv` command.
`mv FILE1 FILE2`

`FILE1` AND `FILE2` are required and positional. No flags.

**Comment by FlorianRappl** [comment]
I think this is also possible using `set_default<T>` instead of `set_required<T>` / `set_optional<T>`. The `set_default` is essentially specifying what to get when no argument is given / applicable. It accepts a bool to determine whether the default arguments are required (`true`) or not (`false`).

Does this cover your scenario or am I on the wrong track again?

**Comment by rhd** [comment]
Hmm... maybe. But there are issues.

given this code:

``` c++
    cli::Parser parser(argc, argv);
    parser.set_optional<std::string>("i", "inPath", ".", "Input directory.");
    parser.set_default<std::vector<std::string> >(true, "List of directories");
    parser.run_and_exit_if_error();
```

The output is:

```
$ ./myapp -h 
The parameter  is required.
List of directories
For more help use --help or -h.
```

Also, how do you get the vector of defaults? 

This should also be valid, right?

``` c++
    parser.set_default<std::string>(true, "First directory");
    parser.set_default<std::vector<std::string> >(false, "Other directories");
```

**Comment by FlorianRappl** [comment]
Hm the second one is not working as currently there can only be one definition of a default argument (a default argument is treated like a normal one with empty strings as short and long option, i.e., you just overwrite the first one with the second).

This also explains how you get the (vector of) defaults: a call to `get<T>` with `T` being your `std::list<std::string>` and the name being the empty string should be ok.

The problem with the help parameter you see here is I think the one discussed in #4. Even though this was closed there is a bigger problem behind it and I wanted to work on it for a longer time. Potentially, I will take care of it today or this weekend. I will flag this issue as a bug and enhancement to remind me to work on it.
