### ISSUE TITLE
How to get a flag

### ISSUE THREAD

**Issue by RobertBakaric** [FlorianRappl/CmdParser#6]
Hi,

Sorry for bugging you, but I have a question. So I've been reading your code and it seams to me there is no way to handle flags. Could it be?? The behaviour I need is, every time i call -h of --help, all other options are not to be evaluated but the usage() ought to be printed. For that to work I would need to evaluate if the call to -h has been made but it seams there is no way to evaluate the flat , just if  a parameter has been assigned to it or not, right? Could you maybe point me to the right direction on how to enable that (if I'm not seeing the option)

thnx

PS great library

PS
PS

I see that this question has been rased for --help option. I mean one can easily add something like:

bool help = false
...
if ( std::find(_arguments.begin(), _arguments.end(), "--help") != _arguments.end() ||
   std::find(_arguments.begin(), _arguments.end(), "-h") != _arguments.end())
   help = true;
...

if (command->required && !command->handled && help == false) ....

in run() function to quick "fix"  the help behaviour. 

but i see no flag handling solution so i guess the one does not exist. (This was not a negative critique, the library is really great. Thnx!! I am definitely gonn start using it from now on. plus if i manage to find some time before you I'll definitely integrate the set_flag() option )

**Comment by FlorianRappl** [comment]
Such flags are essentially booleans, so you would just assign the short name and alias and use the `<bool>` template. Then the flag has been set if the boolean is true. However, what is currently not working (and sorry, I think I promised this for months but I had no time to implement this) is a combination of flags, e.g., passing `-abc` for flags `-a`, `-b`, and `-c`.

Does this answer your question / help your or am I on the wrong track?

**Comment by RobertBakaric** [comment]
ok so if I try 

``` cpp
parser.set_optional<short>("x", "xxx", "flag .");
```

it does not compile. If:

``` cpp
parser.set_required<short>("x", "xxx", "flag .");
```

it works in case:

```
./flag -x 1 
Print  1
```

```
./flag -x 0 
Print  0
```

that is fine. but what I am looking is a more simpler (for a user) flag without the associated parameter, something like:

./flag -x  
Print  1

./flag  
Print  0

 yes I understand that i could achieve what I need by assigning a value to my -x  but i need this to be an optional flag so that when called it returns 1/true and when not is set to 0/false.  I dont' mean to be picky, I'm just wondering if it si possible to achieve this or not. So far I see no such possibility. 

thnx

**Comment by FlorianRappl** [comment]
Take the following from the readme:

``` cpp
parser.set_optional<bool>("a", "all", false, "Boolean arguments are simply switched when encountered, i.e. false to true if provided.");
```

So I think the following might work for you:

``` cpp
parser.set_optional<bool>("x", "xxx", false, "flag ."); //did not work before since you did not specify the default value
```

Optionals require a standard value, as otherwise their value would be undefined (they are optional after all - so users may decide to omit them).

Now the example that you've shown (`./flag -x`) should work.

Hope this helped!

**Comment by RobertBakaric** [comment]
yes it did. Thnx

**Comment by FlorianRappl** [comment]
Glad that it worked! You're welcome!
