### ISSUE TITLE
Backward compatibility 

### ISSUE THREAD

**Issue by ermilindwalekar** [FlorianRappl/CmdParser#9]
Hey that was nifty, thanks!

Working great with C++ 11 and above, I wonder how can this be used without C++11, and should backward compatibility be addressed?

I'd like to pick that up and give you a PR.

**Comment by FlorianRappl** [comment]
Hm, I only thought about C++11 when I developed it. I guess with a lot of conditional areas it would be possible, however, it would certainly not make the code more beautiful / readable.

If you have a good approach then yes - any contribution is welcome!
